[service.mvt]
viewer = true

[[datasource]]
name = "NL.IMRO.0200.bp1148-vas1"
path = "/conf/data/NL.IMRO.0200.bp1148-vas1-simplified-linear.gml"

[grid.user]
width = 256
height = 256
extent = { minx = -285401.920, miny = 22598.080, maxx = 595401.920, maxy = 903401.920 }
srid = 28992
units = "m"
resolutions = [3440.640,1720.320,860.160,430.080,215.040,107.520,53.760,26.880,13.440,6.720,3.360,1.680,0.840,0.420,0.210,0.105,0.0575]
origin = "BottomLeft"

[[tileset]]
name = "NL.IMRO.0200.bp1148-vas1"

[[tileset.layer]]
name = "Plangebied"
datasource = "NL.IMRO.0200.bp1148-vas1"
table_name = "Plangebied"
geometry_field = "geometryProperty"
geometry_type = "MULTIPOLYGON"
buffer_size = 0
simplify = false

[[tileset.layer]]
name = "Planobject"
datasource = "NL.IMRO.0200.bp1148-vas1"
table_name = "Planobject"
geometry_field = "geometryProperty"
geometry_type = "MULTIPOLYGON"
buffer_size = 0
simplify = false

[cache.file]
base = "/var/cache/mvtcache"

[webserver]
bind = "0.0.0.0"
port = 8080