version: '3'
services:

  trex:
    image: busybox
    volumes:
      - ./data:/data
      - scripts:/scripts

  tippecanoe:
    image: klokantech/tippecanoe
    volumes:
      - ./data:/data
      - scripts:/scripts
    env_file:
      - .env

  gdal:
    image: geodata/gdal
    volumes:
      - ./data:/data
      - scripts:/scripts

  tegola:
    image: busybox
    volumes:
      - ./data:/data
      - scripts:/scripts

volumes:
  scripts:

