version: '3'
services:

  trex:
    image: sourcepole/t-rex
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./log:/log

  tippecanoe:
    image: klokantech/tippecanoe
    volumes:
      - ./data:/data
      - ./log:/log

  gdal:
#    image: gdaldocker:latest
    build:
      context: .
      dockerfile: Dockerfile.gdal
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./log:/log
    working_dir: /scripts

  tegola:
    image: busybox
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./log:/log

volumes:
  scripts:

