version: '3'
services:

  trex:
    image: busybox
    volumes:
      - ./data:/data

  tippecanoe:
    image: busybox
    volumes:
      - ./data:/data

  gdal:
    image: geodata/gdal
    volumes:
      - ./data:/data

  tegola:
    image: busybox
    volumes:
      - ./data:/data


